services:
  - type: web
    name: kanban-backend
    env: node
    plan: free
    region: oregon
    root: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    branch: master
    autoDeploy: true
